services:
  db:
    container_name: "RefInDB"
    image: postgres:18.3
    volumes:
      - "./.development/postgresql:/var/lib/postgresql:rw"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-refin}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    restart: unless-stopped
  mailpit:
    image: axllent/mailpit
    container_name: "RefInMailpit"
    restart: unless-stopped
    volumes:
      - "./.development/mailpit/data:/data"
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
