"""create user_certificate table

Revision ID: 00a75923e092
Revises: 8a7e15e9272a
Create Date: 2026-04-09 16:15:25.542669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '00a75923e092'
down_revision: Union[str, Sequence[str], None] = '8a7e15e9272a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_certificate',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('issuing_organization', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('issuing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expire_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credential_id', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('credential_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_certificate_id'), 'user_certificate', ['id'], unique=False)
    op.create_index(op.f('ix_user_certificate_user_profile_id'), 'user_certificate', ['user_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_certificate_user_profile_id'), table_name='user_certificate')
    op.drop_index(op.f('ix_user_certificate_id'), table_name='user_certificate')
    op.drop_table('user_certificate')
    # ### end Alembic commands ###
