"""add_job_nationality_table

Revision ID: 1191548d39b0
Revises: efe293ad5330
Create Date: 2026-05-09 16:46:51.275191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1191548d39b0'
down_revision: Union[str, Sequence[str], None] = 'efe293ad5330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_nationality',
    sa.Column('nationality', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_nationality_id'), 'job_nationality', ['id'], unique=False)
    op.create_index(op.f('ix_job_nationality_job_id'), 'job_nationality', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_nationality_job_id'), table_name='job_nationality')
    op.drop_index(op.f('ix_job_nationality_id'), table_name='job_nationality')
    op.drop_table('job_nationality')
    # ### end Alembic commands ###
