"""create user_language table

Revision ID: 17c33e4840f0
Revises: 00a75923e092
Create Date: 2026-04-09 16:30:03.072274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '17c33e4840f0'
down_revision: Union[str, Sequence[str], None] = '00a75923e092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_language',
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('proficiency_level', sa.Enum('elementary', 'limited_working', 'professional_working', 'full_professional', 'native_bilingual', name='proficiencylevel'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_language_id'), 'user_language', ['id'], unique=False)
    op.create_index(op.f('ix_user_language_user_profile_id'), 'user_language', ['user_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_language_user_profile_id'), table_name='user_language')
    op.drop_index(op.f('ix_user_language_id'), table_name='user_language')
    op.drop_table('user_language')
    # ### end Alembic commands ###
