"""notifications_table

Revision ID: 1a6bde7a676b
Revises: fda9fd013b8f
Create Date: 2026-05-10 14:00:12.762562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1a6bde7a676b'
down_revision: Union[str, Sequence[str], None] = 'fda9fd013b8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('is_seen', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('job_application',
    sa.Column('status', sa.Enum('sent', 'reviewed', 'rejected', 'accepted_for_interview', name='jobapplicationstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_user_job')
    )
    op.create_index(op.f('ix_job_application_id'), 'job_application', ['id'], unique=False)
    op.create_index(op.f('ix_job_application_job_id'), 'job_application', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_application_user_id'), 'job_application', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_column('user', 'name')
    op.add_column('user_profile', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=75), nullable=True))
    op.create_index(op.f('ix_user_profile_name'), 'user_profile', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_name'), table_name='user_profile')
    op.drop_column('user_profile', 'name')
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=75), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.drop_index(op.f('ix_job_application_user_id'), table_name='job_application')
    op.drop_index(op.f('ix_job_application_job_id'), table_name='job_application')
    op.drop_index(op.f('ix_job_application_id'), table_name='job_application')
    op.drop_table('job_application')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_table('notification')
    # ### end Alembic commands ###
