"""Re-create schema

Revision ID: 1be8c8dc947f
Revises: 
Create Date: 2026-04-09 17:51:57.015484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1be8c8dc947f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=75), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_table('user_profile',
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('about', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_id'), 'user_profile', ['id'], unique=True)
    op.create_index(op.f('ix_user_profile_user_id'), 'user_profile', ['user_id'], unique=True)
    op.create_table('user_certificate',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('issuing_organization', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('issuing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expire_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credential_id', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('credential_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_certificate_id'), 'user_certificate', ['id'], unique=False)
    op.create_index(op.f('ix_user_certificate_user_profile_id'), 'user_certificate', ['user_profile_id'], unique=False)
    op.create_table('user_experience',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'self_employed', 'freelance', 'contract', 'internship', 'apprenticeship', 'seasonal', name='employmenttype'), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('location', sa.Enum('on_site', 'hybrid', 'remote', name='locationtype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_experience_id'), 'user_experience', ['id'], unique=False)
    op.create_index(op.f('ix_user_experience_user_profile_id'), 'user_experience', ['user_profile_id'], unique=False)
    op.create_table('user_language',
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('proficiency_level', sa.Enum('elementary', 'limited_working', 'professional_working', 'full_professional', 'native_bilingual', name='proficiencylevel'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_language_id'), 'user_language', ['id'], unique=False)
    op.create_index(op.f('ix_user_language_user_profile_id'), 'user_language', ['user_profile_id'], unique=False)
    op.create_table('user_link',
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_link_id'), 'user_link', ['id'], unique=False)
    op.create_index(op.f('ix_user_link_user_profile_id'), 'user_link', ['user_profile_id'], unique=False)
    op.create_table('user_project',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_project_id'), 'user_project', ['id'], unique=False)
    op.create_index(op.f('ix_user_project_user_profile_id'), 'user_project', ['user_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_project_user_profile_id'), table_name='user_project')
    op.drop_index(op.f('ix_user_project_id'), table_name='user_project')
    op.drop_table('user_project')
    op.drop_index(op.f('ix_user_link_user_profile_id'), table_name='user_link')
    op.drop_index(op.f('ix_user_link_id'), table_name='user_link')
    op.drop_table('user_link')
    op.drop_index(op.f('ix_user_language_user_profile_id'), table_name='user_language')
    op.drop_index(op.f('ix_user_language_id'), table_name='user_language')
    op.drop_table('user_language')
    op.drop_index(op.f('ix_user_experience_user_profile_id'), table_name='user_experience')
    op.drop_index(op.f('ix_user_experience_id'), table_name='user_experience')
    op.drop_table('user_experience')
    op.drop_index(op.f('ix_user_certificate_user_profile_id'), table_name='user_certificate')
    op.drop_index(op.f('ix_user_certificate_id'), table_name='user_certificate')
    op.drop_table('user_certificate')
    op.drop_index(op.f('ix_user_profile_user_id'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_id'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
