"""create user_link table

Revision ID: 1c6d9ee5aeb2
Revises: f91684973cbd
Create Date: 2026-04-09 15:55:08.079408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1c6d9ee5aeb2'
down_revision: Union[str, Sequence[str], None] = 'f91684973cbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_link',
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_link_id'), 'user_link', ['id'], unique=False)
    op.create_index(op.f('ix_user_link_user_profile_id'), 'user_link', ['user_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_link_user_profile_id'), table_name='user_link')
    op.drop_index(op.f('ix_user_link_id'), table_name='user_link')
    op.drop_table('user_link')
    # ### end Alembic commands ###
