"""Create job table

Revision ID: 2a78155aaebd
Revises: 809dfe851426
Create Date: 2026-05-06 14:42:19.003904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '2a78155aaebd'
down_revision: Union[str, Sequence[str], None] = '809dfe851426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('about_the_employer', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('duration', sa.Enum('contract', 'project', name='jobduration'), nullable=False),
    sa.Column('type', sa.Enum('full_time', 'part_time', name='jobtype'), nullable=False),
    sa.Column('location', sa.Enum('remote', 'hybrid', 'on_site', name='joblocation'), nullable=False),
    sa.Column('looking_for', sa.Enum('immigrants', 'refugees', 'displaced', 'all', name='joblookingfor'), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('apply_on_site', sa.Boolean(), nullable=False),
    sa.Column('apply_url', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_id'), 'job', ['id'], unique=False)
    op.create_index(op.f('ix_job_user_id'), 'job', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_user_id'), table_name='job')
    op.drop_index(op.f('ix_job_id'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
