"""Rename hash to token hash

Revision ID: 2f8a007abda5
Revises: 64718943fb36
Create Date: 2026-04-17 23:35:05.355121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '2f8a007abda5'
down_revision: Union[str, Sequence[str], None] = '64718943fb36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset', sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_password_reset_hash'), table_name='password_reset')
    op.create_index(op.f('ix_password_reset_token_hash'), 'password_reset', ['token_hash'], unique=True)
    op.drop_column('password_reset', 'hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset', sa.Column('hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_password_reset_token_hash'), table_name='password_reset')
    op.create_index(op.f('ix_password_reset_hash'), 'password_reset', ['hash'], unique=True)
    op.drop_column('password_reset', 'token_hash')
    # ### end Alembic commands ###
