"""Create job application table

Revision ID: 3783ffbf0985
Revises: efe293ad5330
Create Date: 2026-05-09 14:17:08.350616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3783ffbf0985'
down_revision: Union[str, Sequence[str], None] = 'efe293ad5330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_application',
    sa.Column('status', sa.Enum('sent', 'reviewed', 'rejected', 'accepted_for_interview', name='jobapplicationstatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_id', name='uq_user_job')
    )
    op.create_index(op.f('ix_job_application_id'), 'job_application', ['id'], unique=False)
    op.create_index(op.f('ix_job_application_job_id'), 'job_application', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_application_user_id'), 'job_application', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_application_user_id'), table_name='job_application')
    op.drop_index(op.f('ix_job_application_job_id'), table_name='job_application')
    op.drop_index(op.f('ix_job_application_id'), table_name='job_application')
    op.drop_table('job_application')
    # ### end Alembic commands ###
