"""Add email table

Revision ID: 4f804ccb6394
Revises: 7e33315e568a
Create Date: 2026-04-16 17:01:37.633630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4f804ccb6394'
down_revision: Union[str, Sequence[str], None] = '7e33315e568a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification',
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_id'), 'email_verification', ['id'], unique=False)
    op.create_index(op.f('ix_email_verification_token_hash'), 'email_verification', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_verification_user_id'), 'email_verification', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_verification_user_id'), table_name='email_verification')
    op.drop_index(op.f('ix_email_verification_token_hash'), table_name='email_verification')
    op.drop_index(op.f('ix_email_verification_id'), table_name='email_verification')
    op.drop_table('email_verification')
    # ### end Alembic commands ###
