"""move name to user profile from user table

Revision ID: 600c08cd7259
Revises: 3783ffbf0985
Create Date: 2026-05-09 15:19:36.645637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '600c08cd7259'
down_revision: Union[str, Sequence[str], None] = '3783ffbf0985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_column('user', 'name')
    op.add_column('user_profile', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=75), nullable=True))
    op.create_index(op.f('ix_user_profile_name'), 'user_profile', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_name'), table_name='user_profile')
    op.drop_column('user_profile', 'name')
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=75), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    # ### end Alembic commands ###
