"""add profile picture and banner

Revision ID: 7e33315e568a
Revises: 922fcd33b458
Create Date: 2026-04-13 20:42:46.043839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '7e33315e568a'
down_revision: Union[str, Sequence[str], None] = '922fcd33b458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('profile_picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user_profile', sa.Column('banner', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'banner')
    op.drop_column('user_profile', 'profile_picture')
    # ### end Alembic commands ###
