"""create user_education and user_skill tables

Revision ID: 922fcd33b458
Revises: 1be8c8dc947f
Create Date: 2026-04-09 22:56:44.216257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '922fcd33b458'
down_revision: Union[str, Sequence[str], None] = '1be8c8dc947f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_education',
    sa.Column('school', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('degree', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('major', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_education_id'), 'user_education', ['id'], unique=False)
    op.create_index(op.f('ix_user_education_user_profile_id'), 'user_education', ['user_profile_id'], unique=False)
    op.create_table('user_skill',
    sa.Column('skill', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_skill_id'), 'user_skill', ['id'], unique=False)
    op.create_index(op.f('ix_user_skill_user_profile_id'), 'user_skill', ['user_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_skill_user_profile_id'), table_name='user_skill')
    op.drop_index(op.f('ix_user_skill_id'), table_name='user_skill')
    op.drop_table('user_skill')
    op.drop_index(op.f('ix_user_education_user_profile_id'), table_name='user_education')
    op.drop_index(op.f('ix_user_education_id'), table_name='user_education')
    op.drop_table('user_education')
    # ### end Alembic commands ###
