"""bootstrap database

Revision ID: efe293ad5330
Revises: 
Create Date: 2026-05-08 23:31:01.541819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'efe293ad5330'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=75), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=75), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('email_verification',
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verification_id'), 'email_verification', ['id'], unique=False)
    op.create_index(op.f('ix_email_verification_token_hash'), 'email_verification', ['token_hash'], unique=True)
    op.create_index(op.f('ix_email_verification_user_id'), 'email_verification', ['user_id'], unique=True)
    op.create_table('job',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('position', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('about_the_employer', sqlmodel.sql.sqltypes.AutoString(length=5000), nullable=False),
    sa.Column('duration', sa.Enum('contract', 'project', name='jobduration'), nullable=False),
    sa.Column('type', sa.Enum('full_time', 'part_time', name='jobtype'), nullable=False),
    sa.Column('location', sa.Enum('remote', 'hybrid', 'on_site', name='joblocation'), nullable=False),
    sa.Column('looking_for', sa.Enum('immigrants', 'refugees', 'displaced', 'all', name='joblookingfor'), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('apply_on_site', sa.Boolean(), nullable=False),
    sa.Column('apply_url', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_id'), 'job', ['id'], unique=False)
    op.create_index(op.f('ix_job_user_id'), 'job', ['user_id'], unique=False)
    op.create_table('password_reset',
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_id'), 'password_reset', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_token_hash'), 'password_reset', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_user_id'), 'password_reset', ['user_id'], unique=True)
    op.create_table('user_profile',
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('about', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('profile_picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('banner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_id'), 'user_profile', ['id'], unique=True)
    op.create_index(op.f('ix_user_profile_user_id'), 'user_profile', ['user_id'], unique=True)
    op.create_table('job_language',
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('proficiency_level', sa.Enum('elementary', 'limited_working', 'professional_working', 'full_professional', 'native_bilingual', name='proficiencylevel'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_language_id'), 'job_language', ['id'], unique=False)
    op.create_index(op.f('ix_job_language_job_id'), 'job_language', ['job_id'], unique=False)
    op.create_table('user_certificate',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('issuing_organization', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('issuing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expire_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('credential_id', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('credential_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_certificate_id'), 'user_certificate', ['id'], unique=False)
    op.create_index(op.f('ix_user_certificate_user_profile_id'), 'user_certificate', ['user_profile_id'], unique=False)
    op.create_table('user_education',
    sa.Column('school', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('degree', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('major', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_education_id'), 'user_education', ['id'], unique=False)
    op.create_index(op.f('ix_user_education_user_profile_id'), 'user_education', ['user_profile_id'], unique=False)
    op.create_table('user_experience',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'self_employed', 'freelance', 'contract', 'internship', 'apprenticeship', 'seasonal', name='employmenttype'), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('location', sa.Enum('on_site', 'hybrid', 'remote', name='locationtype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_experience_id'), 'user_experience', ['id'], unique=False)
    op.create_index(op.f('ix_user_experience_user_profile_id'), 'user_experience', ['user_profile_id'], unique=False)
    op.create_table('user_language',
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('proficiency_level', sa.Enum('elementary', 'limited_working', 'professional_working', 'full_professional', 'native_bilingual', name='proficiencylevel'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_language_id'), 'user_language', ['id'], unique=False)
    op.create_index(op.f('ix_user_language_user_profile_id'), 'user_language', ['user_profile_id'], unique=False)
    op.create_table('user_link',
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_link_id'), 'user_link', ['id'], unique=False)
    op.create_index(op.f('ix_user_link_user_profile_id'), 'user_link', ['user_profile_id'], unique=False)
    op.create_table('user_project',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=250), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_project_id'), 'user_project', ['id'], unique=False)
    op.create_index(op.f('ix_user_project_user_profile_id'), 'user_project', ['user_profile_id'], unique=False)
    op.create_table('user_skill',
    sa.Column('skill', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_skill_id'), 'user_skill', ['id'], unique=False)
    op.create_index(op.f('ix_user_skill_user_profile_id'), 'user_skill', ['user_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_skill_user_profile_id'), table_name='user_skill')
    op.drop_index(op.f('ix_user_skill_id'), table_name='user_skill')
    op.drop_table('user_skill')
    op.drop_index(op.f('ix_user_project_user_profile_id'), table_name='user_project')
    op.drop_index(op.f('ix_user_project_id'), table_name='user_project')
    op.drop_table('user_project')
    op.drop_index(op.f('ix_user_link_user_profile_id'), table_name='user_link')
    op.drop_index(op.f('ix_user_link_id'), table_name='user_link')
    op.drop_table('user_link')
    op.drop_index(op.f('ix_user_language_user_profile_id'), table_name='user_language')
    op.drop_index(op.f('ix_user_language_id'), table_name='user_language')
    op.drop_table('user_language')
    op.drop_index(op.f('ix_user_experience_user_profile_id'), table_name='user_experience')
    op.drop_index(op.f('ix_user_experience_id'), table_name='user_experience')
    op.drop_table('user_experience')
    op.drop_index(op.f('ix_user_education_user_profile_id'), table_name='user_education')
    op.drop_index(op.f('ix_user_education_id'), table_name='user_education')
    op.drop_table('user_education')
    op.drop_index(op.f('ix_user_certificate_user_profile_id'), table_name='user_certificate')
    op.drop_index(op.f('ix_user_certificate_id'), table_name='user_certificate')
    op.drop_table('user_certificate')
    op.drop_index(op.f('ix_job_language_job_id'), table_name='job_language')
    op.drop_index(op.f('ix_job_language_id'), table_name='job_language')
    op.drop_table('job_language')
    op.drop_index(op.f('ix_user_profile_user_id'), table_name='user_profile')
    op.drop_index(op.f('ix_user_profile_id'), table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index(op.f('ix_password_reset_user_id'), table_name='password_reset')
    op.drop_index(op.f('ix_password_reset_token_hash'), table_name='password_reset')
    op.drop_index(op.f('ix_password_reset_id'), table_name='password_reset')
    op.drop_table('password_reset')
    op.drop_index(op.f('ix_job_user_id'), table_name='job')
    op.drop_index(op.f('ix_job_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_email_verification_user_id'), table_name='email_verification')
    op.drop_index(op.f('ix_email_verification_token_hash'), table_name='email_verification')
    op.drop_index(op.f('ix_email_verification_id'), table_name='email_verification')
    op.drop_table('email_verification')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
