"""create user_experience table

Revision ID: f5af39d5bfb2
Revises: 17c33e4840f0
Create Date: 2026-04-09 17:08:18.146673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'f5af39d5bfb2'
down_revision: Union[str, Sequence[str], None] = '17c33e4840f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_experience',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'self_employed', 'freelance', 'contract', 'internship', 'apprenticeship', 'seasonal', name='employmenttype'), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('location', sa.Enum('on_site', 'hybrid', 'remote', name='locationtype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_profile_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_experience_id'), 'user_experience', ['id'], unique=False)
    op.create_index(op.f('ix_user_experience_user_profile_id'), 'user_experience', ['user_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_experience_user_profile_id'), table_name='user_experience')
    op.drop_index(op.f('ix_user_experience_id'), table_name='user_experience')
    op.drop_table('user_experience')
    # ### end Alembic commands ###
